kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: mjkaye/mycroft-debian-slim
    tags: latest-amd64

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: docker-build-arm
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.arm32v7
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: mjkaye/mycroft-debian-slim
    tags: latest-arm

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: docker-build-arm64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: mjkaye/mycroft-debian-slim
    tags: latest-arm64

---
kind: pipeline
name: push_manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: mjkaye/mycroft-debian-slim:latest
    template: mjkaye/mycroft-debian-slim:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

depends_on:
- amd64
- arm64
- arm
